controllerManager:
  kubeRbacProxy:
    args:
    - --secure-listen-address=0.0.0.0:8443
    - --upstream=http://127.0.0.1:8080/
    - --logtostderr=true
    - --v=0
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: gcr.io/kubebuilder/kube-rbac-proxy
      tag: v0.13.1
    # -- Define resources requests and limits for RBAC proxy
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 5m
        memory: 64Mi
  manager:
    args:
    - --health-probe-bind-address=:8081
    - --metrics-bind-address=127.0.0.1:8080
    - --leader-elect
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: ghcr.io/ihyoudou/backblaze-operator
      tag: latest
    # -- Define resources requests and limits for backblaze-operator
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
  replicas: 1
  serviceAccount:
    annotations: {}
# -- Credentials for Backblaze B2 Master Application Key
credentials:
  # -- Use Backblaze B2 credentials from existing secret
  secret:
    # -- Use existing secret instead of providing credentials in values (true/false)
    useSecret: false
    # -- Name of secret with B2 credentials
    name: ""
  # -- Backblaze B2 Master Application Key ID
  b2ApplicationId: ""
  # -- Backblaze B2 Master Application Key Key
  b2ApplicationKey: ""
  # -- Backblaze B2 Region of account
  b2Region: ""
kubernetesClusterDomain: cluster.local
metricsService:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  type: ClusterIP
