apiVersion: v1
kind: Secret
metadata:
  name: credentials
type: Opaque
data:
  B2_REGION: {{ .Values.b2.region | base64 }}
  B2_APPLICATION_ID: {{ .Values.b2.applicationId | base64 }}
  B2_APPLICATION_KEY: {{ .Values.b2.applicationKey | base64 }}
