apiVersion: v1
kind: Service
metadata:
  name: {{ include "backblaze-operator.fullname" . }}-service
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: b2operator
    app.kubernetes.io/part-of: b2operator
    control-plane: controller-manager
  {{- include "backblaze-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    control-plane: controller-manager
  {{- include "backblaze-operator.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.metricsService.ports | toYaml | nindent 2 -}}