apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "backblaze-operator.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: b2operator
    app.kubernetes.io/part-of: b2operator
  {{- include "backblaze-operator.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}