{{- if not .Values.credentials.secret.useSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backblaze-operator.fullname" . }}-credentials
  labels:
  {{- include "backblaze-operator.labels" . | nindent 4 }}
data:
  B2_APPLICATION_ID: {{ required "credentials.b2ApplicationId is required" .Values.credentials.b2ApplicationId
    | b64enc | quote }}
  B2_APPLICATION_KEY: {{ required "credentials.b2ApplicationKey is required" .Values.credentials.b2ApplicationKey
    | b64enc | quote }}
  B2_REGION: {{ required "credentials.b2Region is required" .Values.credentials.b2Region
    | b64enc | quote }}
type: Opaque
{{- end -}}