apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "backblaze-operator.fullname" . }}-manager-role
  labels:
  {{- include "backblaze-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - b2.issei.space
  resources:
  - buckets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - b2.issei.space
  resources:
  - buckets/finalizers
  verbs:
  - update
- apiGroups:
  - b2.issei.space
  resources:
  - buckets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - b2.issei.space
  resources:
  - keys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - b2.issei.space
  resources:
  - keys/finalizers
  verbs:
  - update
- apiGroups:
  - b2.issei.space
  resources:
  - keys/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "backblaze-operator.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: b2operator
    app.kubernetes.io/part-of: b2operator
  {{- include "backblaze-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "backblaze-operator.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "backblaze-operator.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'